services:
  - name: citycare-backend
    type: web
    env: docker
    branch: main
    region: singapore           
    rootDir: server
    dockerfilePath: Dockerfile
    instanceType: starter
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        value: ""              
      - key: JWT_SECRET
        value: ""            
      - key: RESEND_API_KEY
        value: ""              
      - key: APP_BASE_URL
        value: ""              
      - key: FRONTEND_URL
        value: ""            
      - key: GOOGLE_CLIENT_ID
        value: ""             

  - name: citycare-frontend
    type: web
    env: docker
    branch: main
    region: singapore
    rootDir: client
    dockerfilePath: Dockerfile
    # instanceType: starter
    envVars:
      - key: VITE_API_BASE_URL
        value: "/"            
